name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    secrets:
      MY_SECRET_QUOTE:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic Flask test
        run: |
          python app.py &
          sleep 5
          curl -v http://127.0.0.1:5000/quote

      - name: Print secret quote
        run: |
          echo "Secret from reusable: ${{ secrets.MY_SECRET_QUOTE }}"
