---
name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      flask-port:
        required: true
        type: string
      test-path:
        required: true
        type: string
    secrets:
      MY_SECRET_QUOTE:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Debug Python Version
        run: python --version

      - name: Print secret quote (securely)
        run: echo "Secret Quote: ${{ secrets.MY_SECRET_QUOTE }}"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic Flask test
        run: |
          python app.py &
          sleep 5
          curl -v http://127.0.0.1:${{ inputs.flask-port }}/${{ inputs.test-path }}
