---
name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      flask-port:
        required: true
        type: string
      test-path:
        required: true
        type: string
    secrets:
