---
name: CI - Flask Quote API (Caller)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-reusable-ci:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      python-version: "3.10.13"
    secrets:
      MY_SECRET_QUOTE: ${{ secrets.MY_SECRET_QUOTE }}
