name: CI - Flask Quote API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Debug Python Version
        run: python --version

      - name: Print secret quote (securely)
        run: echo "Secret Quote: ${{ secrets.MY_SECRET_QUOTE }}"

      - name: Install dependencies
        run: |
          set -e
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic Flask app test
        run: |
          set -e
          python app.py &
          sleep 5
          curl -v http://127.0.0.1:5000/quote
