name: CI - Matrix Reusable Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-reusable:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10.13"]

    uses: ./.github/workflows/ci-reusable.yml
    with:
      python-version: ${{ matrix.python-version }}
      flask-port: "5000"
      test-path: "quote"
    secrets:
      MY_SECRET_QUOTE: ${{ secrets.MY_SECRET_QUOTE }}
