---
name: CI - Flask Quote API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Show Python version
        run: python --version

      - name: Print secret quote (securely)
        run: |
          echo "Secret Quote: ${{ secrets.MY_SECRET_QUOTE }}"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic Flask test
        run: |
          python app.py &
          sleep 5
          curl http://127.0.0.1:5000/quote
