name: CI - Flask Quote API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      python-version: "3.10.13"
      flask-port: "5000"
      test-path: "quote"
    secrets:
      MY_SECRET_QUOTE: ${{ secrets.MY_SECRET_QUOTE }}
